version: '3.4'

services:

  tinyurl:
    build: .
    ports:
      - 8000:8000
    links:
      - cassandra
      - kgs


  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
    volumes:
      - "./src/main/resources/cassandra-init.sh:/cassandra-init.sh"
      - "./src/main/resources/import.cql:/import.cql"
    command: "sh /cassandra-init.sh"

  redis:
    image: redis:alpine

  kgs:
    image: victuxbb/tinyurlkgs
    environment:
      KGS_REDIS_HOST: redis
      KGS_KEYS_LENGTH: 3
    links:
      - redis
